titleBase: SwissArmyKnife
base: /swissarmyknife/
favicon: images/logo.svg
lang: en

social:
  - name: GitHub
    url: https://github.com/turkananation/swissarmyknife
  - name: Pub.dev
    url: https://pub.dev/packages/swissarmyknife
  - name: API Reference
    url: https://pub.dev/documentation/swissarmyknife/latest/
