name: Dart CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    analyze-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dart-lang/setup-dart@v1
              with:
                  sdk: "stable"
            - run: dart pub get
            - run: dart format --output=none --set-exit-if-changed .
            - run: dart analyze
            - run: dart test --coverage
            - run: dart pub publish --dry-run
